// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCgzcHRsJ7sItHKLfT1QPh1H-dMJF08Vko',
    appId: '1:507808446603:web:2b02602e2e92f30f433c8e',
    messagingSenderId: '507808446603',
    projectId: 'flutter-todo-app-df1c3',
    authDomain: 'flutter-todo-app-df1c3.firebaseapp.com',
    storageBucket: 'flutter-todo-app-df1c3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn8RDpYCtcQVkq9hHfwfSiVxkMZMhieAE',
    appId: '1:507808446603:android:0621b07a07ae2666433c8e',
    messagingSenderId: '507808446603',
    projectId: 'flutter-todo-app-df1c3',
    storageBucket: 'flutter-todo-app-df1c3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3KDECrIdZbsRqdL4fcwm3x8PQdI_lUJE',
    appId: '1:507808446603:ios:34c843af34dc3357433c8e',
    messagingSenderId: '507808446603',
    projectId: 'flutter-todo-app-df1c3',
    storageBucket: 'flutter-todo-app-df1c3.appspot.com',
    iosClientId: '507808446603-f1ttagu72j4ddg2384j46uicon6fc1gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3KDECrIdZbsRqdL4fcwm3x8PQdI_lUJE',
    appId: '1:507808446603:ios:34c843af34dc3357433c8e',
    messagingSenderId: '507808446603',
    projectId: 'flutter-todo-app-df1c3',
    storageBucket: 'flutter-todo-app-df1c3.appspot.com',
    iosClientId: '507808446603-f1ttagu72j4ddg2384j46uicon6fc1gc.apps.googleusercontent.com',
    iosBundleId: 'com.example.todo',
  );
}
